version: "3"

services:
  postgres:
    container_name: postgres
    ports:
      - 5432:5432
    image: postgres:alpine
    environment:
      - POSTGRES_USER=turboAf
      - POSTGRES_PASSWORD=getTurbo
      - POSTGRES_DB=prisma
    restart: always
    volumes:
      - database:/var/lib/postgresql/data

  mongo:
    container_name: mongo
    image: mongo:5
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./volumes/mongo:/data/db

  firebase-emulators:
    container_name: firebase-emulators
    ports:
      - 4000:4000
      - 4001:4001
      - 4002:4002
    build:
      context: ./lib/firebase-emulators
      dockerfile: Dockerfile
    image: firebase-emulator:firebase-emulator
    volumes:
      - ./lib/firebase-emulators/firebase.json:/src/firebase.json
      - ./lib/firebase-emulators/storage.rules:/src/storage.rules
      - ./lib/firebase-emulators/seed:/src/firebase/seed
    command: firebase emulators:start --project dev --import=./firebase/seed --debug

volumes:
  database:
    driver: local
