version: "3"

services:
  mongo:
    container_name: mongo
    image: mongo:5
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongodata:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 5001:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/

  firebase-emulators:
    container_name: firebase-emulators
    ports:
      - "4000:4000"
      - "4001:4001"
      - "4002:4002"
    build:
      context: ./firebase-emulators
      dockerfile: Dockerfile
    image: firebase-emulator:firebase-emulator
    volumes:
      - ./firebase-emulators/firebase.json:/src/firebase.json
      - ./firebase-emulators/storage.rules:/src/storage.rules
      - ./seeds/firebase:/src/seeds/firebase
    command: firebase emulators:start --project dev --import=./seeds/firebase

  api:
    container_name: api
    build:
      context: ./api
      dockerfile: Dockerfile
    depends_on:
      - mongo
      - firebase-emulators
    ports:
      - 5000:5000
    volumes:
      - ./api:/home/node/app
    environment:
      - DB_CONNECTION_STRING=mongodb://root:example@mongo:27017/myFirstDatabase
      - ENVIRONMENT=DEVELOPMENT
      - FIREBASE_AUTH_EMULATOR_HOST=firebase-emulators:4001
      - FIREBASE_STORAGE_EMULATOR_HOST=firebase-emulators:4002
      - TWITCH_CLIENT_ID=${TWITCH_CLIENT_ID}
      - TWITCH_CLIENT_SECRET=${TWITCH_CLIENT_SECRET}
      - TWITCH_EXTENSION_SECRET=${TWITCH_EXTENSION_SECRET}
    command: npm run local

  web:
    container_name: web
    depends_on:
      - mongo
      - firebase-emulators
    ports:
      - 3000:3000
    build:
      context: ./web
      dockerfile: Dockerfile.dev
    environment:
      - DB_CONNECTION_STRING=mongodb://root:example@mongo:27017/myFirstDatabase
      - ENVIRONMENT=DEVELOPMENT
      - NEXT_PUBLIC_ENVIRONMENT=DEVELOPMENT
      - FIREBASE_AUTH_EMULATOR_HOST=firebase-emulators:4001
      - FIREBASE_STORAGE_EMULATOR_HOST=firebase-emulators:4002
      - NEXT_PUBLIC_FIREBASE_AUTH_EMULATOR_HOST=localhost:4001
      - NEXT_PUBLIC_FIREBASE_STORAGE_EMULATOR_HOST=localhost:4002
      - NEXT_PUBLIC_SOCKET_HOST=http://localhost:5000
      - TWITCH_CLIENT_ID=${TWITCH_CLIENT_ID}
      - TWITCH_CLIENT_SECRET=${TWITCH_CLIENT_SECRET}
    volumes:
      - ./web:/src

volumes:
  mongodata:
