version: "3"

services:
  # mongo:
  #   container_name: mongo
  #   image: mongo:5
  #   restart: always
  #   ports:
  #     - 27017:27017
  #   volumes:
  #     - mongodata:/data/db
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: root
  #     MONGO_INITDB_ROOT_PASSWORD: example

  firebase-emulators:
    container_name: firebase-emulators
    ports:
      - "4000:4000"
      - "4001:4001"
      - "4002:4002"
    build:
      context: ./firebase-emulators
      dockerfile: Dockerfile
    image: firebase-emulator:firebase-emulator
    volumes:
      - ./firebase-emulators/firebase.json:/src/firebase.json
      - ./firebase-emulators/storage.rules:/src/storage.rules
      - ./seeds/firebase:/src/seeds/firebase
    command: firebase emulators:start --project dev --import=./seeds/firebase

  api:
    container_name: api
    build:
      context: ./api
      dockerfile: Dockerfile
    depends_on:
      - mongo
      - firebase-emulators
    ports:
      - 5000:5000
    volumes:
      - ./api:/src
    environment:
      - DB_CONNECTION_STRING=mongo://root:example@localhost:27017/myFirstDatabase
      - ENVIRONMENT=TESTING
      - FIREBASE_AUTH_EMULATOR_HOST=firebase-emulators:4001
      - FIREBASE_STORAGE_EMULATOR_HOST=firebase-emulators:4002
      - TWITCH_CLIENT_ID=${TWITCH_CLIENT_ID}
      - TWITCH_CLIENT_SECRET=${TWITCH_CLIENT_SECRET}
    command: npm run local

  web:
    container_name: web
    build:
      context: ./web
      dockerfile: Dockerfile
      args:
        - DB_CONNECTION_STRING=mongo://root:example@localhost:27017/myFirstDatabase
        - ENVIRONMENT=TESTING
        - NEXT_PUBLIC_ENVIRONMENT=TESTING
        - FIREBASE_AUTH_EMULATOR_HOST=firebase-emulators:4001
        - FIREBASE_STORAGE_EMULATOR_HOST=firebase-emulators:4002
        - NEXT_PUBLIC_FIREBASE_AUTH_EMULATOR_HOST=localhost:4001
        - NEXT_PUBLIC_FIREBASE_STORAGE_EMULATOR_HOST=localhost:4002
        - NEXT_PUBLIC_SOCKET_HOST=http://localhost:5000
        - TWITCH_CLIENT_ID=${TWITCH_CLIENT_ID}
        - TWITCH_CLIENT_SECRET=${TWITCH_CLIENT_SECRET}
    depends_on:
      - mongo
      - firebase-emulators
    ports:
      - 3000:3000
    environment:
      - DB_CONNECTION_STRING=mongo://root:example@localhost:27017/myFirstDatabase
      - ENVIRONMENT=TESTING
      - NEXT_PUBLIC_ENVIRONMENT=TESTING
      - FIREBASE_AUTH_EMULATOR_HOST=firebase-emulators:4001
      - FIREBASE_STORAGE_EMULATOR_HOST=firebase-emulators:4002
      - NEXT_PUBLIC_FIREBASE_AUTH_EMULATOR_HOST=localhost:4001
      - NEXT_PUBLIC_FIREBASE_STORAGE_EMULATOR_HOST=localhost:4002
      - NEXT_PUBLIC_SOCKET_HOST=http://localhost:5000
      - TWITCH_CLIENT_ID=${TWITCH_CLIENT_ID}
      - TWITCH_CLIENT_SECRET=${TWITCH_CLIENT_SECRET}

volumes:
  mongodata:
