name: Deploy Testing Environment and run E2E

on:
  pull_request:
    branches:
      - master

jobs:  
  build:  
    runs-on: ubuntu-latest
    if: github.repository_owner == 'kittrgg'
    steps:
      - uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push api testing image
        uses: docker/build-push-action@v2
        with:
          context: ./api
          push: true
          tags: ghcr.io/${{github.repository}}/api:test-${{github.sha}}

      - name: Build and push web testing image
        uses: docker/build-push-action@v2
        with:
          context: ./web
          push: true
          tags: ghcr.io/${{github.repository}}/web:test-${{github.sha}}
          build-args: |
            ENVIRONMENT=${{secrets.CI_ENVIRONMENT}}
            NEXT_PUBLIC_ENVIRONMENT=${{secrets.CI_ENVIRONMENT}}
            DB_CONNECTION_STRING=${{secrets.CI_DB_CONNECTION_STRING}}
            NEXT_PUBLIC_GOOGLE_ANALYTICS=${{secrets.CI_NEXT_PUBLIC_GOOGLE_ANALYTICS}}
            NEXT_PUBLIC_API_KEY=${{secrets.CI_NEXT_PUBLIC_API_KEY}}
            NEXT_PUBLIC_FIREBASE_DATABASE_URL=${{secrets.CI_NEXT_PUBLIC_FIREBASE_DATABASE_URL}}
            NEXT_PUBLIC_ROLLBAR_ACCESS_TOKEN=${{secrets.CI_NEXT_PUBLIC_ROLLBAR_ACCESS_TOKEN}}
            NEXT_PUBLIC_ROLLBAR_ENVIRONMENT=${{secrets.CI_NEXT_PUBLIC_ROLLBAR_ENVIRONMENT}}
            FIREBASE_PROJECT_ID=${{secrets.CI_FIREBASE_PROJECT_ID}}
            FIREBASE_AUTH_DOMAIN=${{secrets.CI_FIREBASE_AUTH_DOMAIN}}
            FIREBASE_CLIENT_EMAIL=${{secrets.CI_FIREBASE_CLIENT_EMAIL}}
            FIREBASE_MESSAGING_SENDER_ID=${{secrets.CI_FIREBASE_MESSAGING_SENDER_ID}}
            FIREBASE_APP_ID=${{secrets.CI_FIREBASE_APP_ID}}
            FIREBASE_MEASUREMENT_ID=${{secrets.CI_FIREBASE_MEASUREMENT_ID}}
            FIREBASE_COOKIE_SECRET_PREVIOUS=${{secrets.CI_FIREBASE_COOKIE_SECRET_PREVIOUS}}
            FIREBASE_COOKIE_SECRET_CURRENT=${{secrets.CI_FIREBASE_COOKIE_SECRET_CURRENT}}
            TWITCH_CLIENT_ID=${{secrets.CI_TWITCH_CLIENT_ID}}
            TWITCH_CLIENT_SECRET=${{secrets.CI_TWITCH_CLIENT_SECRET}}
            NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=${{secrets.CI_NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY}}
            STRIPE_SECRET_KEY=${{secrets.CI_STRIPE_SECRET_KEY}}
            STRIPE_WEBHOOK_SECRET=${{secrets.CI_STRIPE_WEBHOOK_SECRET}}
            SUBSCRIPTION_PRICE_ID=${{secrets.CI_SUBSCRIPTION_PRICE_ID}}
            MONTHLY_TIP_PRICE_ID=${{secrets.CI_MONTHLY_TIP_PRICE_ID}}
            NEXT_PUBLIC_SOCKET_HOST=${{secrets.CI_NEXT_PUBLIC_SOCKET_HOST}}
            GOOGLE_APPLICATION_CREDENTIALS=${{secrets.CI_GOOGLE_APPLICATION_CREDENTIALS}}

    # Just could not get these to work.
    # - name: Delete old api images
    #   uses: actions/delete-package-versions@v2
    #   with:
    #     package-name: "api"
    #     token: ${{secrets.GITHUB_TOKEN}}
    #     min-versions-to-keep: 3
    # - name: Delete old web images
    #   uses: actions/delete-package-versions@v2
    #   with:
    #     package-name: "web"
    #     token: ${{secrets.GITHUB_TOKEN}}
    #     min-versions-to-keep: 3

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.repository_owner == 'kittrgg'
    steps:
      - name: Trigger api testing deployment to Digital Ocean
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.DOKKU_HOST}}
          username: ${{secrets.DOKKU_SSH_USER}}
          key: "${{ secrets.DOKKU_SSH_PRIVATE_KEY }}"
          script: |
            dokku git:from-image stage-api ghcr.io/${{github.repository}}/api:test-${{github.sha}}

      - name: Trigger web testing deployment to Digital Ocean
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.DOKKU_HOST}}
          username: ${{secrets.DOKKU_SSH_USER}}
          key: "${{ secrets.DOKKU_SSH_PRIVATE_KEY }}"
          script: |
            dokku git:from-image stage-web ghcr.io/${{github.repository}}/web:test-${{github.sha}}

  e2e:
    needs: deploy
    runs-on: ubuntu-latest
    if: github.repository_owner == 'kittrgg'
    steps:
      - uses: actions/checkout@v2

      - name: Cypress run
        uses: cypress-io/github-action@v2
