name: Deploy Testing Environment and run E2E

on:
  # pull_request:
  #   branches:
  #     - master
  push:
    branches:
      - stage

jobs:
  build-and-unit-test:
    concurrency:
      group: ${{ github.ref }}
      cancel-in-progress: true
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{matrix.node-version}}
        uses: actions/setup-node@v2
        with:
          node-version: ${{matrix.node-version}}

      # - name: Cache dependencies
      #   uses: actions/cache@v2
      #   with:
      #     path: ~/.npm
      #     key: npm-${{ hashFiles('package-lock.json') }}
      #     restore-keys: npm-

      - name: Install dependencies
        run: yarn install

      - name: Migrate DB
        env:
          DATABASE_URL: ${{secrets.CI_DATABASE_URL}}
        run: cd packages/prisma && npx prisma migrate deploy

      - name: Run build
        env:
          NEXT_PUBLIC_ADS_DISABLED: true
          NEXT_PUBLIC_ENABLE_SEEDING: true
          NEXT_PUBLIC_ENVIRONMENT: ${{secrets.CI_NODE_ENV}}
          DB_CONNECTION_STRING: ${{secrets.CI_DB_CONNECTION_STRING}}
          DATABASE_URL: ${{secrets.CI_DATABASE_URL}}
          NEXT_PUBLIC_GOOGLE_ANALYTICS: ${{secrets.CI_NEXT_PUBLIC_GOOGLE_ANALYTICS}}
          NEXT_PUBLIC_API_KEY: ${{secrets.CI_NEXT_PUBLIC_API_KEY}}
          NEXT_PUBLIC_FIREBASE_DATABASE_URL: ${{secrets.CI_NEXT_PUBLIC_FIREBASE_DATABASE_URL}}
          FIREBASE_PROJECT_ID: ${{secrets.CI_FIREBASE_PROJECT_ID}}
          FIREBASE_AUTH_DOMAIN: ${{secrets.CI_FIREBASE_AUTH_DOMAIN}}
          FIREBASE_CLIENT_EMAIL: ${{secrets.CI_FIREBASE_CLIENT_EMAIL}}
          FIREBASE_MESSAGING_SENDER_ID: ${{secrets.CI_FIREBASE_MESSAGING_SENDER_ID}}
          FIREBASE_APP_ID: ${{secrets.CI_FIREBASE_APP_ID}}
          FIREBASE_MEASUREMENT_ID: ${{secrets.CI_FIREBASE_MEASUREMENT_ID}}
          FIREBASE_COOKIE_SECRET_PREVIOUS: ${{secrets.CI_FIREBASE_COOKIE_SECRET_PREVIOUS}}
          FIREBASE_COOKIE_SECRET_CURRENT: ${{secrets.CI_FIREBASE_COOKIE_SECRET_CURRENT}}
          TWITCH_CLIENT_ID: ${{secrets.CI_TWITCH_CLIENT_ID}}
          TWITCH_SECRET: ${{secrets.CI_TWITCH_SECRET}}
          NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: ${{secrets.CI_NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY}}
          STRIPE_SECRET_KEY: ${{secrets.CI_STRIPE_SECRET_KEY}}
          STRIPE_WEBHOOK_SECRET: ${{secrets.CI_STRIPE_WEBHOOK_SECRET}}
          SUBSCRIPTION_PRICE_ID: ${{secrets.CI_SUBSCRIPTION_PRICE_ID}}
          MONTHLY_TIP_PRICE_ID: ${{secrets.CI_MONTHLY_TIP_PRICE_ID}}
          NEXT_PUBLIC_SOCKET_HOST: ${{secrets.CI_NEXT_PUBLIC_SOCKET_HOST}}
          GOOGLE_APPLICATION_CREDENTIALS: ${{secrets.CI_GOOGLE_APPLICATION_CREDENTIALS}}
          NEXT_PUBLIC_SENTRY_DSN: ${{secrets.SENTRY_DSN}}
          SENTRY_AUTH_TOKEN: ${{secrets.SENTRY_AUTH_TOKEN}}
          SENTRY_LOG_LEVEL: debug
        run: yarn build --scope=\"api\" --scope=\"web\" --include-dependencies --token="${{ secrets.TURBO_SERVER_TOKEN }}" --team="kittr"

      - name: Run unit tests
        run: yarn test

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push api testing image
        uses: docker/build-push-action@v2
        with:
          context: ./apps/api
          push: true
          tags: ghcr.io/${{github.repository}}/api:test-${{github.sha}}

      - name: Build and push web testing image
        uses: docker/build-push-action@v2
        with:
          context: ./apps/web
          push: true
          tags: ghcr.io/${{github.repository}}/web:test-${{github.sha}}


  deploy:
    concurrency:
      group: ${{ github.ref }}
      cancel-in-progress: true
    needs: build-and-unit-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Trigger api testing deployment to Digital Ocean
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.DOKKU_HOST}}
          username: ${{secrets.DOKKU_SSH_USER}}
          key: "${{ secrets.DOKKU_SSH_PRIVATE_KEY }}"
          script: |
            dokku git:from-image stage-api ghcr.io/${{github.repository}}/api:test-${{github.sha}}

      - name: Trigger web testing deployment to Digital Ocean
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.DOKKU_HOST}}
          username: ${{secrets.DOKKU_SSH_USER}}
          key: "${{ secrets.DOKKU_SSH_PRIVATE_KEY }}"
          script: |
            dokku git:from-image stage-web ghcr.io/${{github.repository}}/web:test-${{github.sha}}

  e2e:
    concurrency:
      group: ${{ github.ref }}
      cancel-in-progress: true
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          working-directory: ./lib/e2e
          config-file: config.ci.json